import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { createPrismaClient } from "@/src/infrastructure/prisma/client";
import { readConfirmationToken } from "@/src/server/confirmation";
import { getSessionActorId } from "@/src/server/session";
import { validateStoredClaim } from "@/src/server/stored-claim-validation";
class BlockingValidationError extends Error { constructor(readonly issues: ReturnType<typeof validateStoredClaim>) { super("claim has blocking validation issues"); } }
export async function POST(request: Request, context: { params: Promise<{ claimId: string }> }) { try { const actorId = getSessionActorId(request); const { claimId } = await context.params; const body = await request.json() as { confirmationToken?: unknown }; if (typeof body.confirmationToken !== "string") throw new Error("invalid confirmation"); const confirmation = readConfirmationToken(body.confirmationToken); if (!confirmation || confirmation.claimId !== claimId || confirmation.actorId !== actorId) throw new Error("invalid confirmation"); const prisma = db(); const result = await prisma.$transaction(async (tx) => { const claim = await tx.claimDraft.findUnique({ where: { id: claimId }, include: { receipts: { select: { id: true, extractionPayload: true } }, expenseItems: true, validationResults: { where: { code: { in: ["DUPLICATE_FILE", "DUPLICATE_INVOICE"] }, resolvedAt: null } } } }); if (!claim || claim.employeeId !== actorId) throw new Error("forbidden"); if (claim.version !== confirmation.version) throw new Error("confirmation is stale"); const issues = validateStoredClaim(claim); if (issues.some((issue) => issue.severity === "BLOCKING")) throw new BlockingValidationError(issues); const totalAmountCents = claim.expenseItems.reduce((sum, item) => sum + item.amountCents, 0); const updated = await tx.claimDraft.updateMany({ where: { id: claimId, version: claim.version, status: { not: "SUBMITTED" } }, data: { status: "SUBMITTED", version: { increment: 1 } } }); if (updated.count !== 1) throw new Error("confirmation is stale"); const snapshot = await tx.submissionSnapshot.create({ data: { claimId, claimVersion: claim.version, submissionNumber: `RB${new Date().getFullYear()}${randomUUID().replaceAll("-", "").slice(0, 10)}`, payload: { purpose: claim.purpose, totalAmountCents, expenseItems: claim.expenseItems } } }); await tx.auditEvent.create({ data: { claimId, actorId, type: "CLAIM_SUBMITTED", payload: { submissionNumber: snapshot.submissionNumber } } }); return snapshot; }); return NextResponse.json(result, { status: 201 }); } catch (error) { if (error instanceof BlockingValidationError) return NextResponse.json({ error: "请先处理提交前检查中的阻断项。", issues: error.issues }, { status: 409 }); const message = error instanceof Error ? error.message : "request failed"; return NextResponse.json({ error: message }, { status: message === "confirmation is stale" ? 409 : message === "unauthenticated" ? 401 : message === "forbidden" ? 403 : 400 }); } }
function db() { if (!process.env.DATABASE_URL) throw new Error("database configuration is missing"); return createPrismaClient(process.env.DATABASE_URL); }
